version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: file-api-db
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: files
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./folder_permission_system
    container_name: file-api-backend
    restart: always
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: test_user
      DATABASE_PASSWORD: test_password
      DATABASE_NAME: files
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./folder_permission_system/uploads:/app/uploads

volumes:
  pgdata:
