openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Permission:
      type: object
      properties:
        userId:
          type: string
          format: uuid
          description: ID of the user
        fileId:
          type: string
          format: uuid
          description: ID of the file
        canRead:
          type: boolean
          description: Whether the user can read the file
        canWrite:
          type: boolean
          description: Whether the user can write to the file
        canDelete:
          type: boolean
          description: Whether the user can delete the file
paths:
  /files: 
    get:
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: query
          required: true
          description: to get the files that this user has read access
          schema:
            type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not Found